### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by engineersamuel** [EasyGraphQL/easygraphql-tester#142]
I have a valid Query that passes with `tester.test` however when I `tester.mock` with a fixture, then I'm seeing:

```
TypeError: Cannot read property 'type' of undefined
      at validateFixture (node_modules/easygraphql-tester/utils/fixture.js:50:27)
      at validateFixture (node_modules/easygraphql-tester/utils/fixture.js:100:19)
```

I debugged and it appears the issue is related to a simple `name` of type `String` which the mocker has no `selectedType`, hence the error at this line: https://github.com/EasyGraphQL/easygraphql-tester/blob/master/utils/fixture.js#L46

```
  if (schema[selectedType.type]) {
```

If I simply add a null check, all my tests pass:

```
  if (selectedType && schema[selectedType.type]) {
```

I'm happy to open a PR here, but I'd first want a core dev here to weigh in on what might be the issue and if this would be a valid check to simply add a null check on `selectedType`

**Comment by estrada9166** [comment]
Thanks for creating this issue! can you share a quick example to reproduce it please! thanks!

**Comment by engineersamuel** [comment]
@estrada9166 Sure thing, here it is: https://github.com/engineersamuel/easygraphqlrepro with instructions.

**Comment by estrada9166** [comment]
Thanks for sharing it! what I can notice is that you are missing on the GraphQL schema, the field `storageAccountName` that is being tried to be mock

If you update it for - it may work
```graphql
type StorageDirectory {
  name: String!
  storageAccountName: String!
  files(sampleSize: Int): [StorageFile]
}
```

Definitely something that can be improves is the error message in this case in case you want to open a PR!

**Comment by engineersamuel** [comment]
Ahhh, great catch!  Not sure on my bandwidth for a PR here, but let's leave this open and I'll try to get to it.
