### ISSUE TITLE
Test query of scalar type doesn't work

### ISSUE THREAD

**Issue by leosuncin** [EasyGraphQL/easygraphql-tester#43]
It fails when try to query a scalar type not an object, and get ``TypeError: Cannot read property 'selections' of undefined``

You can try the next example code:
```js
const EasyGraphQLTester = require('easygraphql-tester')
const typeDefs = `
type Query {
  name: String!
}
`
const tester = new EasyGraphQLTester(typeDefs)

tester.test(true, `{
  name
}`)
```
Stacktrace:
```
node_modules/easygraphql-tester/lib/queryParser.js:35
    parsedType.fields = selectedFields(element.selectionSet.selections)
                                                            ^

TypeError: Cannot read property 'selections' of undefined
    at selections.forEach.element (node_modules/easygraphql-tester/lib/queryParser.js:35:61)
    at Array.forEach (<anonymous>)
    at queryBuilder (node_modules/easygraphql-tester/lib/queryParser.js:31:14)
    at queryParser (node_modules/easygraphql-tester/lib/queryParser.js:111:19)
    at Tester.mock (node_modules/easygraphql-tester/lib/tester.js:24:25)
    at Tester.test (node_modules/easygraphql-tester/lib/tester.js:68:12)
    at Object.<anonymous> (backend/__test__/test.js:10:10)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

**Comment by estrada9166** [comment]
@leosuncin Thank you so much for reporting it! 

I'm working on it to solve it ASAP!

**Comment by estrada9166** [comment]
@leosuncin There is a new version that solves this issue!!

Thanks!! if you think is missing something, we can reopen again this issue!
